### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by jalvar53** [aleochoam/Otto#2]
Pongan aca lo que se les ocurra, lo vamos chuleando:

- [ ] Contar trolleadas para llevar la cuenta, puede irse restando con pasadas de verga
- [ ] Hacer callar a Carlos cuando escriba mucho por Discord (2 mensajes seguidos)
- [ ] Insultar al mono con Amazon Polly
- [ ] Usar audios propios para situaciones ("Chepe valiste monda", "Porque nadie me da like", etc...)

**Comment by aleochoam** [comment]
This project is no longer mantained, so please implement your own bot.
